name: test_dart_mongo
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  http_server: ^1.0.0
  mongo_dart: ^0.7.0+1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
